/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.2 Torus.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Torus.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Torus_Baked" geometry={nodes.Torus_Baked.geometry} material={materials['Torus_Baked.001']} scale={[1, -0.016, 1]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Torus.glb')
